#!/bin/bash
parent_dir=$(dirname "$(pwd)")
for file in *.html; do
    if [ ! -e "$parent_dir/$file" ] || [ "$file" -nt "$parent_dir/$file" ]; then
        cp "$file" "$parent_dir/$file"
        echo "Copying $file to $parent_dir"
    fi
done
